# Example configuration file for Homunculus
# Copy this file to ~/.config/homun/config.yml and customize as needed

github:
  # Your GitHub username
  username: bharathcs
  # GitHub base URL (usually doesn't need to be changed)
  base_url: https://github.com

gitea:
  # Your Gitea username (can be different from GitHub username)
  username: bhcs
  # Your Gitea instance URL
  base_url: https://gitea.example.com
